url: "https://abunning.uk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/blog/" # the subpath of your site, e.g. /blog
title: "Andrew Bunning" # the name of your site, e.g. ACME Corp.
remote_theme: pages-themes/tactile@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Configure page URL strucutres to remove the default /categories at the start
permalink: /blog/:year/:month/:slug

# Configure the pagination
paginate: 2
paginate_path: "/blog/page:num/"
